name: C++ CI

on:
  push:
    branches: 
    - feature/*
  pull_request:
    branches: 
    - main 
    - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake

    - name: Build project
      run: |
        mkdir -p build
        cd build
        cmake ..
        make

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
