services:

  backend:
    build: .
    container_name: backend-sensor-sensei
    environment:
      - NODE_ENV=development
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: database-sensor-sensei
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - sensor_sensei_data:/var/lib/postgresql/data

volumes:
  sensor_sensei_data: