name: PlatformIO CI for TTGO T-Beam

on:
  push:
    branches: 
      - feature/*
  pull_request:
    branches: 
      - main 
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Cache PlatformIO
        uses: actions/cache@v3
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-platformio-${{ hashFiles('**/platformio.ini') }}
          restore-keys: |
            ${{ runner.os }}-platformio-

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: Build firmware
        run: platformio run --environment ttgo-t-beam

      - name: Run unit tests
        run: platformio test --environment ttgo-t-beam

      - name: List build directory
        run: ls -al .pio/build/ttgo-t-beam/
